[package]
name = "eo"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-s3 = "0.14.0"
aws-config = "0.14.0"
tokio = { version = "1.0", features = ["full"] }
tempfile = "3.3"
anyhow = "1.0"
notify = "5.2"
clap = { version = "4.0", features = ["derive"] }
google-cloud-storage = "0.22.1"
